name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 30.2
      - name: Install dependencies
        run: make install-deps
      - name: Byte compile
        run: make compile
      - name: Run tests
        run: make test
