name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: cat-emacs/.github/.github/workflows/emacs-package.yml@v1
    with:
      install-command: make install-deps
      check-command: make compile test
